### ISSUE TITLE
Text in "bioinsight" 

### ISSUE THREAD

**Issue by moeslund** [Xjph/observatory-docs#3]
Hi thank you for all your work with the "elite observatory"

After updating to 1.0.3 the columns in the bioinsight tap, is very compressed, and not very readable 

Tried googling around to try to solve the issue myself, but can't seem to find any good answer

Hope you could find time to write an solution to me

Kind regards Michael
![bio](https://github.com/user-attachments/assets/13f0f8e9-07c9-4dc7-9197-1f5ffa948758)

**Comment by Xjph** [comment]
This is not the correct repository for reporting [issues with Observatory.](https://github.com/Xjph/ObservatoryCore/issues).

That said, this is just out of date bioinsights. Grab the latest observatory and bioinsights and this should be resolved.
